{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyOxpb6JILSVCSbdNnPOJbk2",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/thureinmyoag/MMDT_T-PY102_Batch01/blob/main/lab06.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 12,
      "metadata": {
        "id": "q-OqlgFuglnU"
      },
      "outputs": [],
      "source": [
        "# -------------------------\n",
        "# Do not change the below Code\n",
        "# -------------------------\n",
        "def helper_fun1_(arr, i):\n",
        "    while i > 0:\n",
        "        parent = (i - 1) // 2\n",
        "        if arr[i] < arr[parent]:\n",
        "            arr[i], arr[parent] = arr[parent], arr[i]\n",
        "            i = parent\n",
        "        else:\n",
        "            break\n",
        "\n",
        "    return arr\n",
        "\n",
        "def helper_fun2_(arr, i):\n",
        "    n = len(arr)\n",
        "\n",
        "    while True:\n",
        "        left = 2 * i + 1\n",
        "        right = 2 * i + 2\n",
        "        smallest = i\n",
        "        if left < n and arr[left] < arr[smallest]:\n",
        "            smallest = left\n",
        "        if right < n and arr[right] < arr[smallest]:\n",
        "            smallest = right\n",
        "        if smallest != i:\n",
        "            arr[i], arr[smallest] = arr[smallest], arr[i]\n",
        "            i = smallest\n",
        "        else:\n",
        "            break\n",
        "    return arr\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# Q1 — schedule_next_job\n",
        "# ------------------------------------------------------------\n",
        "# A cloud system maintains a job list where each job has a\n",
        "# priority score (smaller value = higher priority).\n",
        "#\n",
        "# The system must always be able to quickly access (O(1)) the job\n",
        "# with the highest priority (smallest score).\n",
        "#\n",
        "# You are given the current job list (arr) and a new job\n",
        "# (priority_score).\n",
        "#\n",
        "# Write a function to add a new job into the system\n",
        "# and and reorganize the list so that the priority rule is maintained.\n",
        "\n",
        "# IMPORTANT:\n",
        "# - You may use the provided helper functions to adjust the structure.\n",
        "# - Do NOT implement any additional helper functions.\n",
        "# ------------------------------------------------------------\n",
        "\n",
        "def schedule_next_job(jobs, new_job):\n",
        "    jobs.append(new_job)\n",
        "    return helper_fun1_(jobs, len(jobs) - 1)\n",
        "\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# Q2 — process_next_job\n",
        "# ------------------------------------------------------------\n",
        "# A system processes jobs based on priority score\n",
        "# (smaller value = higher priority).\n",
        "#\n",
        "# The job with the highest priority is always processed first.\n",
        "#\n",
        "# Given the current job list (arr), remove and return the\n",
        "# next job to process.\n",
        "#\n",
        "# After removal, reorganize the list to maintain the\n",
        "# priority rule.\n",
        "#\n",
        "# IMPORTANT:\n",
        "# - You may use the provided helper functions to adjust the structure.\n",
        "# - Do NOT implement any additional helper functions.\n",
        "#\n",
        "# ------------------------------------------------------------\n",
        "\n",
        "def process_next_job(arr):\n",
        "    if len(arr) == 0:\n",
        "        return None\n",
        "\n",
        "    # TODO: return removed job and updated list\n",
        "\n",
        "    next_job = arr[0]\n",
        "\n",
        "    if len(arr) == 1:\n",
        "        arr.pop()\n",
        "    else:\n",
        "        # Move the last element to the root\n",
        "        arr[0] = arr[-1]\n",
        "        arr.pop()\n",
        "        # Restore the min‑heap property by sifting down from the root\n",
        "        helper_fun2_(arr, 0)\n",
        "\n",
        "    return next_job,arr\n",
        "\n",
        "# ------------------------------------------------------------\n",
        "# Q3 — personal priority reflection\n",
        "# ------------------------------------------------------------\n",
        "# This question is about reflecting on your personal priorities.\n",
        "#\n",
        "# You are given a structure where each item is:\n",
        "#     (weight, category)\n",
        "#\n",
        "# Smaller weight = higher priority.\n",
        "#\n",
        "# Instructions:\n",
        "# 1. Change the weights (numbers) based on YOUR priorities.\n",
        "# 2. Do NOT change the category names.\n",
        "# 3. Insert a new category (\"security\") with your chosen weight.\n",
        "# 4. Maintain the structure using the provided helper function.\n",
        "#\n",
        "# NOTE:\n",
        "# - There is NO single correct answer.\n",
        "# - Focus on meaningful weights based on your perspective.\n",
        "# - Do NOT create additional helper functions.\n",
        "# ------------------------------------------------------------\n",
        "\n",
        "def personal_priority_q():\n",
        "    priorty_q = [\n",
        "        (5, \"education\"),\n",
        "        (2, \"family\"),\n",
        "        (1, \"health\"),\n",
        "        (3, \"friends\"),\n",
        "        (4, \"money\")\n",
        "    ]\n",
        "    # TODO: append new_item to personal_priorty_q\n",
        "    new_item = (6, \"security\")\n",
        "\n",
        "\n",
        "    # TODO: return the list\n",
        "    # highest priority (lowest score) should be always top\n",
        "\n",
        "    for i in range(len(priorty_q)):\n",
        "        helper_fun1_(priorty_q, i)\n",
        "\n",
        "    # Insert new item\n",
        "    new_item = (6, \"security\")\n",
        "    priorty_q.append(new_item)\n",
        "    helper_fun1_(priorty_q, len(priorty_q) - 1)\n",
        "\n",
        "    return priorty_q\n",
        "\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "EYc8bqLmlSZW"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}